### ISSUE TITLE
Hello! Not working for me since last update! Curious 

### ISSUE THREAD

**Issue by panchomira** [zanna-37/hass-swipe-navigation#11]
How are you doing? First at all THANK YOU for maintaining this amazing feature for HA. 

Since last update it have been working from time to time, pretty erratic until a few hours back (now it doesn't work anymore). The weird thing is that even tho I tried a downgrade, it still not working (maybe something wrong with the manual install). But, if I install the old repo, from Hacs, it works. Weird, right?

**Comment by BoneheadFraggle** [comment]
I switched to this version of Swipe Navigation a couple of weeks ago. Uninstalled the old one, installed this version from HACS and it worked fine.
I just tried to upgrade 1.5.0 > 1.6.0, also via HACS and after that the swipe no longer worked.
Re-installed 1.5.0 via HACS and it works fine again.

My config:
```
swipe_nav:
  animate: fade
  swipe_amount: 10
  wrap: true
```

**Comment by zanna-37** [comment]
My apologizes for the inconvenience. Everything should be fixed now.
A small typo had much power.

**Comment by BoneheadFraggle** [comment]
Just updated from 1.5.0 incl. existing config - works fine. 

Great work, thanks!
