### ISSUE TITLE
config is not reloaded when changed

### ISSUE THREAD

**Issue by zanna-37** [zanna-37/hass-swipe-navigation#12]
The configuration should be reloaded when...
- [x] ...changing between dashboards with different configurations
- [x] ...changing the configuration with the "Raw configuration editor"

**Comment by dbuezas** [comment]
In Android (Samsung S21) when updating the source (and maybe after updating the version via HACS too) I found it to be necessary to:
* Close the HA App
* Delete HA's App cache 
* Reopen the HA App
For changes to be picked up

**Comment by zanna-37** [comment]
Delete cache should not be necessary.

- On mobile:
  - Close the app, swipe it away from "recent apps", reopen it
- On desktop:
  - Just refresh the page

**Comment by dbuezas** [comment]
I'm thinking about people using a tablet in Kiosk mode. It just stays there forever

**Comment by dbuezas** [comment]
Everything will become sluggish after a while for no good reason

**Comment by zanna-37** [comment]
I think you commented on the wrong issue, otherwise I don't understand how is this related to the config autoreload.

**Comment by dbuezas** [comment]
> I think you commented on the wrong issue, otherwise I don't understand how is this related to the config autoreload.

absolutely, I just deleted the messages. Sorry for that.

Regarding the deleting the cache, maybe it is because of how I transfer the files during development (copy via ssh in the command line). I needed to clear the cache each time I updated the code

**Comment by dbuezas** [comment]
Oh, and I mean changing the source code, not the config.
