### ISSUE TITLE
Swipe animation speed

### ISSUE THREAD

**Issue by dbuezas** [zanna-37/hass-swipe-navigation#18]
Is there any way to speed up the swipe animation? 
Since there is an intermediate blank screen, I think the animation would look best if it was twice as fast 

Really useful card! Thanks for pointing it out to me and keeping it alive.

**Comment by zanna-37** [comment]
Shouldn't be too difficult, I'll have a look at that =)

**Comment by dbuezas** [comment]
I took a look at the code and came up with this:
```javascript

**Comment by dbuezas** [comment]
I took a look at the code and came up with this prototype:

```js
if (animate == "swipe") {
      const DURATION = 200; // this could be configurable now
      const _in = left ? `${screen.width / 2}px` : `-${screen.width / 2}px`; // dividing by 2 now because the easing is fixed
      const _out = left ? `-${screen.width / 2}px` : `${screen.width / 2}px`;
      // removed setting transitionDuration, as this is overwritten by the full transition style
      view.style.transition = `transform ${DURATION}ms ease-in, opacity ${DURATION}ms ease-in`; // ease-in in the first part of the animation. This means start slow and, but don't slow down at the end
      view.style.opacity = 0;
      view.style.transform = `translate(${_in}, 0)`;
      view.ontransitionend=()=>{ // use callback instead of timeouts
        view.ontransitionend = undefined
        tabs[index].dispatchEvent(new MouseEvent("click", { bubbles: false, cancelable: true }));
        view.style.transition = "";
        view.style.transform = `translate(${_out}, 0)`;
        window.getComputedStyle(view, null);          // force repainting. Probably not needed
        setTimeout(()=>{ // give time for HA to react to the click
          view.style.transition = `transform ${DURATION}ms ease-out, opacity ${DURATION}ms ease-out`; // ease-out now
          view.style.opacity = 1;
          view.style.transform = `translate(0px, 0)`;
        }, 40) 
      };
    }
```

I think the swipe feeling is much better now, It doesn't feel like there is an intermediate blank page anymore (mostly the easings)

**Comment by zanna-37** [comment]
Thank you very much!
The transition code is part of the old code and I haven't had the time to rework it yet.
I'll have a look at the pull request but I see the improvement so good job!

**Comment by dbuezas** [comment]
> is part of the old code and I haven't had the time to rework it yet

Everybody else: "I want to leave a legacy"
Programmers: "We call that tech debt"

**Comment by dbuezas** [comment]
With the new easings, the animation doesn't look like it it needs to be faster anymore. The visual effect used to feel like there was an intermediate blank card, that's what I misinterpreted as "it must be slower than I'm used to", but this is fixed in my PR.

Therefore, I'll close this issue, as I don't think configurable durations are needed anymore.

**Comment by zanna-37** [comment]
Thank you very much! I'll keep this open until the pull request is merged.
