### ISSUE TITLE
Scrolling within the plotly card swipes the tab

### ISSUE THREAD

**Issue by dbuezas** [zanna-37/hass-swipe-navigation#20]
I'm not sure if I should preventDefault touch events within the plotly graphs card or if there is an elegant way of "fixing" from within hass-swipe-navigation.

**Comment by dbuezas** [comment]
Alternative solution: 
* Ignore swipe if the time difference between touchstart and touchend goes over s hardcoded theshold

**Comment by zanna-37** [comment]
Wait, is it really swiping?
Because [this line](https://github.com/zanna-37/hass-swipe-navigation/blob/d620cc693efc491a6af7a18d04c589ed4370d871/src/swipe-navigation.ts#L34) is meant to prevent that, and it's working for me.

**Comment by dbuezas** [comment]
Oh, that's odd... It is swiping indeed. I can make a gif later if that helps.
Even if I drag and then stop for seconds before releasing (which was the target of my proposed solution).
But I modified the src, maybe I broke something. There's even the chance that I took the source from the wrong repository by mistake.
I'll double check today

**Comment by zanna-37** [comment]
Be sure you're using the plotly production card, I only tested with that and maybe the -dev one use a different html ID.

**Comment by dbuezas** [comment]
Indeed I had copy pasted the source from some other repo (probably the one this forks).
This issue does indeed not exist in your branch :) 

Anyway, you may want to still consider having a maximum swipe duration to avoid this incompatibility with other "not-accounted for" cards :)
