### ISSUE TITLE
New sliders in 2022.12 are not ommited

### ISSUE THREAD

**Issue by antonio1475** [zanna-37/hass-swipe-navigation#25]
This add-on doesn't work over sliders and that's great.

> Features:
>[...]
>Option to ignore swipes over certain elements (e.g. sliders or maps)

(Although I don't know where the option is. It has worked great by default on all my sliders incl. Mushroom.

However, 2022.12 (released today) introduced the new Features for some Tile cards like lights, and swipe navigation acts when sliding them.

https://www.home-assistant.io/blog/2022/12/07/release-202212/#tile-card-gets-features

Hoping an update can easily fix this, or happy to learn if this needs to be configured on my end.

Thank you :)

**Comment by zanna-37** [comment]
Yeah, I know, the new slider uses a different element. Update is coming in some minutes (v1.7.0).
By the way, there is no need for extra configuration, the exception list is built-in.

**Comment by antonio1475** [comment]
Thanks a lot @zanna-37 for the fast update! It now skips the new Tile slider.

I'm raising a separate issue just to keep things focused 😄
