### ISSUE TITLE
bug : ios three fingers swipe can't switch server

### ISSUE THREAD

**Issue by ritech** [zanna-37/hass-swipe-navigation#31]
bug : ios three fingers swipe can't switch server

**Comment by zanna-37** [comment]
What do you mean by "switch server"?
Describe what you expect (or want) and what happens instead.

**Comment by zanna-37** [comment]
@ritech Can you explain it better?

**Comment by zanna-37** [comment]
Maybe you mean that "a tab should be switched with a 3 finder swipe". However, this plugin only works with a single finger swipe, and I don't see why it should respond to 3 finger.

If you don't agree, please explain your use case and the reasons behind it, and we can discuss it together. =)

If I don't see a reply in some days, I'll close the issue, but you can still comment to explain your idea.
