### ISSUE TITLE
Add 'my-slider-v2' to the swipe exception list 

### ISSUE THREAD

**Issue by Dirksoet** [zanna-37/hass-swipe-navigation#33]
Hopefully I'm committing this the proper way. First time. 

The my-slider is included in this projects' exception list, but that project has been rewritten and is now my-slider-v2 (https://github.com/AnthonMS/my-cards/blob/main/docs/cards/slider-v2.md).
Overarching project (https://github.com/AnthonMS/my-cards)

Could this be added to the exception list? 
I'm using this my-slider-v2 as an element inside another card, would the exception then still work?

Thank you and happy holidays!

**Comment by zanna-37** [comment]
> I'm using this my-slider-v2 as an element inside another card, would the exception then still work?

I should work, but it depends on the wrapping card. We'll find out. 😉

**Comment by zanna-37** [comment]
Try with `v1.10.0` and let me know if everything is working. =)

**Comment by Dirksoet** [comment]
I am sorry for the delay. v1.10.0 solves the issue perfectly. 
Swiping is disabled for the my-slider-v2, even when it's integrated in another card (Vertical Stack In Card)
Thank you very much!

**Comment by zanna-37** [comment]
Glad to help. 🎩
Thank you very much for your contribution. =)
