### ISSUE TITLE
Exception for History explorer card

### ISSUE THREAD

**Issue by mvdwetering** [zanna-37/hass-swipe-navigation#34]
Would it be possible to add the History explorer card as an exeption?
It allows moving the graphs by dragging it left/right which also triggers the swipe.

https://github.com/alexarch21/history-explorer-card

**Comment by zanna-37** [comment]
Yes, added to my TODO list. 👍🏻
Thank you. =)

**Comment by Mick51** [comment]
Hello, will the functionality be created ?  
I'm also interested.

**Comment by zanna-37** [comment]
Yeah, I'm very sorry for the long delay. I'll publish an update very soon.

**Comment by zanna-37** [comment]
My apologies for the delay. Everything should be fixed in `v1.10.1`.
Please, let me know if everything is ok.
Thank you for the contribution!

**Comment by mvdwetering** [comment]
Works, great! 
Thanks for adding it.
