### ISSUE TITLE
Exception for sankey chart

### ISSUE THREAD

**Issue by Floppe** [zanna-37/hass-swipe-navigation#35]
Would it be possible to allow scrolling a sankey chart if it does not fit on screen, without swiping to next?

https://github.com/MindFreeze/ha-sankey-chart

**Comment by zanna-37** [comment]
Yes, I'll probably add it this weekend.

**Comment by zanna-37** [comment]
@Floppe, just a question, how do you make the chart scrollable? It appears to be of a fixed size by default.

**Comment by Floppe** [comment]
It resizes itself pretty good, but 4+ sections does not fit on a mobile screen for me. I have only set height in the sankey code template.

Desktop example:
![image](https://user-images.githubusercontent.com/238729/215833621-8222f646-3fb0-4058-930a-acc366d75e29.png)

Mobile example:
![image](https://user-images.githubusercontent.com/238729/215833770-19b0da7b-b808-44fa-881b-7a6b9f00e39e.png)

**Comment by zanna-37** [comment]
Ok, but, is there a scrollbar or something that can scroll? Otherwise there is no point in adding it in the exceptions.

**Comment by Floppe** [comment]
Ah, I didn't think of that. No, it's the entire view that scrolls. Perhaps I need to start an issue with sankey component first that it should be scrollable if it does not fit in the view.

**Comment by zanna-37** [comment]
Yeah, I think I'll be better. From my point of view, the fact that it doesn't fit the screen when on mobile it's a bug from their side. In the screenshot you provided, the card goes beyond the view limit, and that shouldn't happen in my opinion.

**Comment by zanna-37** [comment]
The issue on Sankey repo is tracked here MindFreeze/ha-sankey-chart#91.

**Comment by zanna-37** [comment]
Everything should be fixed on `v1.11.1`. Let me know. Thanks =)

**Comment by Floppe** [comment]
Yes, v1.11.0 do handle so the view is scrollable when I set a fixed size for all sections.

**Comment by zanna-37** [comment]
Out of curiosity, can you provide the code to set a fixed size for all sections?
