### ISSUE TITLE
Exception request: Tabbed Card

### ISSUE THREAD

**Issue by n00bcodr** [zanna-37/hass-swipe-navigation#36]
Please add an exception for tabbed card

https://github.com/kinghat/tabbed-card

**Comment by zanna-37** [comment]
Is there any scrollable element? If so which one?

**Comment by n00bcodr** [comment]
If there are a few tabs, the tabs can be scrolled 

https://user-images.githubusercontent.com/49611451/218493691-ea91d2f7-dc1e-4b22-95df-a66818e7ea58.mp4

**Comment by zanna-37** [comment]
Amazing! Thanks for the video, in this way I can exclude only the scrollable element, preserving the swipe on the rest. =)

**Comment by n00bcodr** [comment]
Guess that works!

I can test it if you want me to!

**Comment by zanna-37** [comment]
@n00bcodr if you want, you can test the latest pre-release `v1.10.2`. Everything should be fixed. =)
Let me know!

**Comment by n00bcodr** [comment]
Works perfectly!
Thanks!

**Comment by zanna-37** [comment]
Glad to help 🎩
I'm releasing it publicly, thank you for your contribution. =)
