### ISSUE TITLE
Swiping on android has no effect

### ISSUE THREAD

**Issue by jherrera123** [zanna-37/hass-swipe-navigation#39]
On Android, navigating to a dashboard and swiping has no effect

## Steps to reproduce

- Configure multiple dashboards in Home Assistant
- Installed hass swipe navigation via HACS 
- Cleared cache/data from mobile via Android app settings
- Log in to Home Assistant
- Navigate to Overview dashboard
- Swipe left/right
- Nothing happens
- Repeat in other dashboards, including in blank areas
- Nothing happens

## System(s)

- Home Assistant Swipe Navigation v1.10.1
- HACS 1.29.0
- Home Assistant 2022.12.6
- Galaxy S9 with Home Assistant companion app 2023.1.1-full

**Comment by jherrera123** [comment]
I tried the same steps using Chrome on Android rather than the companion app, and it also doesn't work

**Comment by zanna-37** [comment]
Clearing the cache the way you did it has no effect.
The companion app clears the cache when removing the app from "recent". Chrome doesn't have that functionality.
You need to find anorher way to clear cache.

This may help https://stackoverflow.com/questions/18626699/how-to-disable-cache-on-chrome-for-android.
