### ISSUE TITLE
Swipe Exception for Meteo Alarm Card

### ISSUE THREAD

**Issue by JbbDE** [zanna-37/hass-swipe-navigation#43]
Hello, could you please add a swipe exception for the Meteo Alarm Card?

https://github.com/MrBartusek/MeteoalarmCard

Thank you!

![IMG_20230313_160952](https://user-images.githubusercontent.com/70019640/224744333-b94db573-bdb7-440d-8d1a-b7d537e626f3.jpg)

**Comment by JbbDE** [comment]
`type: custom:meteoalarm-card
entity: binary_sensor.warning_r
integration: nina
override_headline: false
entities:
  - entity: binary_sensor.warning_r
  - entity: binary_sensor.warning_r
  - entity: binary_sensor.warning_r
  - entity: binary_sensor.warning_r
  - entity: binary_sensor.warning_r
hide_when_no_warning: true
disable_swiper: false
scaling_mode: scale
`

**Comment by zanna-37** [comment]
Everything should be fixed on `v1.11.1`. Let me know. Thanks =)
