### ISSUE TITLE
Return to default page

### ISSUE THREAD

**Issue by aled2305** [zanna-37/hass-swipe-navigation#44]
Hello, I was wondering if it's possible to configure a timeout feature. For example automatically return to a defined tab after 1 minute of inactivity?

**Comment by zanna-37** [comment]
I feel that this is out-of-scope for this repo since it has been designed to do a "swipe navigation".
Anyway, I think you can find a component that does that, or you can code it yourself with the help of the Home assists community forum. =)

**Comment by pskowronek** [comment]
For other interested, this can be achieved using this hint: https://community.home-assistant.io/t/switch-back-to-default-dashboard-after-some-time/498244/6

**Comment by zanna-37** [comment]
@pskowronek thank you very much for sharing this!
