### ISSUE TITLE
Swipe navigation breaks on 2023.4.0b0

### ISSUE THREAD

**Issue by hmmbob** [zanna-37/hass-swipe-navigation#45]
Subject says it all :-)

Version 1.11.0 installed on latest beta 2023.4.0b0 doesn't work. No errors in the console.

**Comment by zanna-37** [comment]
Very bad indeed! Thank you for the heads-up.

**Comment by zanna-37** [comment]
An update that fixes this will probably be available before the stable HA release. =)
Thanks again.

**Comment by Mick51** [comment]
No trial version yet ?

**Comment by zanna-37** [comment]
Everything should be fixed on `v1.11.1`. Let me know. Thanks =)

**Comment by hmmbob** [comment]
Jep, works! Thanks!

**Comment by markfrancisonly** [comment]
Did the update break the default left-edge swipe-in gesture for expanding a collapsed HA sidebar nav menu?  I have the HA header hidden on our mobile phones so there is no way to expand the responsive sidebar without  the default gesture

**Comment by CRCinAU** [comment]
Still seems like this is broken with 1.11.1 on:

```
Home Assistant 2023.4.1
Frontend 20230406.1 - latest
```

**Comment by hmmbob** [comment]
It's not.

Did you force refresh your browser and/or cleared the cache of the HA app?

**Comment by CRCinAU** [comment]
> cleared the cache of the HA app

Ah - I didn't know this was a thing. That fixed it - thanks for the hint.

I was under the impression that the "There's a new version of the UI" with the RELOAD button did that - but TIL....

**Comment by hmmbob** [comment]
Been there 🤣

**Comment by tekhiegit** [comment]
I have this issue. Cleared cache and made no difference
