### ISSUE TITLE
Swipe Exception for "floor3d-card"

### ISSUE THREAD

**Issue by FragMenthor** [zanna-37/hass-swipe-navigation#48]
Could you please make also an exception for "floor3d-card"? Is is all based on move and click interaction, so it's really mandatory to be usable with swipe-navigation:

https://github.com/adizanni/floor3d-card

Thanks in advance!
FragMenthor

**Comment by zanna-37** [comment]
Sure, I'll add it in the next release.

**Comment by zanna-37** [comment]
Sorry for the delay. Can you test the last pre-release (v1.12.0)? Everything should be working.
