### ISSUE TITLE
Swipe Exception for 'gallery-card'

### ISSUE THREAD

**Issue by jgverweij** [zanna-37/hass-swipe-navigation#51]
Could you please make also an exception for 'gallery-card'? See https://github.com/TarheelGrad1998/gallery-card

Thanks in advance!

**Comment by zanna-37** [comment]
Yes, I'll add this in the next release. =)

**Comment by zanna-37** [comment]
Sorry for the delay. Can you test the last pre-release (v1.12.0)? Everything should be working.

**Comment by jgverweij** [comment]
Perfect! It wasn't immediately effective on my mobile, though I had cleared the cache. But some time later it is now working flawless.
