### ISSUE TITLE
Smoother fade animation

### ISSUE THREAD

**Issue by GreeMart** [zanna-37/hass-swipe-navigation#54]
Hi,
this is an aesthetic request. 

Would it be possibile to add a parameter to fade animation so that the two dashboard overlay for `overlay_%` instead of fade to an empty dashboard between the two?

0% would be no overlay (as it is)
100% would represent overlay for the entire transition time

Thanks for the effort you put into this project.

M.

**Comment by zanna-37** [comment]
When you click on a tab, HomeAssistant replaces the content of the current view with the new one.
Currently, the fade animation consists of:
- fading out the view
- simulate a click on the next tab
- fading in the view

For this reason, I don't think it's possible to have 2 views rendered at once.

_Sorry for the late reply._
