### ISSUE TITLE
skip_tabs not working 

### ISSUE THREAD

**Issue by DarthSonic** [zanna-37/hass-swipe-navigation#58]
I configured swipe_nav: in raw config of dashboard and set skip_tabs: 2 to skip the third tab. Tab is still shown on swipe.

**Comment by DarthSonic** [comment]
Okay. Found a solution myself:

skip_tabs: 2,

works. So need to add a comma at the end. Should work without too IMHO or mentioned in documentation.

**Comment by zanna-37** [comment]
Thank you very much for the issue!
This is indeed a bug and needs to be fixed. I wonder how it stayed there so long without being noticed.

**Comment by zanna-37** [comment]
Can you test the last pre-release (v1.12.1)? Everything should be working.

**Comment by DarthSonic** [comment]
To be honest: I do not know how to test pre-releases ;-)

**Comment by zanna-37** [comment]
It's now available for everybody 👍
