### ISSUE TITLE
Swipe not working once entering edit mode

### ISSUE THREAD

**Issue by bcutter** [zanna-37/hass-swipe-navigation#6]
Tested this successor of the original integration and it works perfectly, as expected (and well-known) 👍 
Unfortunately a former fellow friend seems to still exist, see here for the bug report:

https://github.com/maykar/lovelace-swipe-navigation/issues/55

**Comment by zanna-37** [comment]
Hi @bcutter, the issue should be fixed in the latest release (v1.6.0). Can you update and confirm that everything is working?
Thank you!

**Comment by zanna-37** [comment]
`logger_level` is not mandatory. It was a bug (#11) and now should be fixed.
Can you try the latest release and let me know?
Thank you. =)
