### ISSUE TITLE
Swipe with mouse doesn't work on firefox

### ISSUE THREAD

**Issue by tripplehelix** [zanna-37/hass-swipe-navigation#62]
Client,
Firefox Nightly V119.0a1 (2023-09-11) 
Firefox Beta V118.0b7
On Debian Linux

Server,
Home Assistant 2023.9.1 
Supervisor 2023.08.3 
Operating System 10.5 
Frontend 20230908.0 - latest

**Comment by wernerhp** [comment]
`Uncaught ReferenceError: TouchEvent is not defined`

**Comment by WoBBeLnl** [comment]
Ah, thought I was doing wrong...same issue here in Firefox. Works as a charm in Chrome 👍🏻

**Comment by zanna-37** [comment]
A fix is coming. Sorry for the inconvenience.

**Comment by zanna-37** [comment]
This is what you get when you think
_"Well, it's just a small feature, I don't need a test. What could ever happen?"_
Well, Firefox. Firefox happened. 😂

**Comment by zanna-37** [comment]
Thank you all for spotting the issue.
Can you test the new pre-release `v1.13.1`? Everything should be working.

**Comment by tripplehelix** [comment]
Yep, 1.13.1 fixed it.
