### ISSUE TITLE
`skip_tabs` starts from 0

### ISSUE THREAD

**Issue by costa-alex** [zanna-37/hass-swipe-navigation#7]
Hi,
I have the following configuration on my dashboard:
`swipe_nav:
  prevent_default: true
  swipe_amount: 20
  skip_hidden: true
  wrap: true
  skip_tabs: 5,6`

I have 6 tabs on the dashboard and I want to skip the last two (they are some grafana charts, no need to see those on the mobile). If i'm on the 4th tab and swipe right I want to wrap swipe to the first tab but it goes to the 5th tab, ignoring the skip_tabs configuration.

Dashboard has 6 tabs only, no hidden tabs.

Thanks

**Comment by zanna-37** [comment]
Tabs count starts at `0`.
First tab is `0`, second is `1`, and so on. Try with `skip_tabs: 4,5`.

**Comment by costa-alex** [comment]
That explains it :)

Thanks, it's working now.

**Comment by zanna-37** [comment]
I'll leave it open so I can update the documentation and add this detail.
Thank you!
