### ISSUE TITLE
Feature: go back to first (or default card) after a given time

### ISSUE THREAD

**Issue by pskowronek** [zanna-37/hass-swipe-navigation#70]
Feature: go back to first (or default card) after a given time.

Use case:
- you swipe to other card on your home dashboard to see details of your commute time or weather outside (for example) and you go out
- when you return you would like to see a default dashboard

So, after like X minutes of inactivity a default (first) dashboard should appear automatically.

**Comment by zanna-37** [comment]
Duplicate of https://github.com/zanna-37/hass-swipe-navigation/issues/44.

**Comment by pskowronek** [comment]
Can be achieved using this: https://community.home-assistant.io/t/switch-back-to-default-dashboard-after-some-time/498244/6
