### ISSUE TITLE
Swipe navigation isn't compatible with Grace grag 'n' drop

### ISSUE THREAD

**Issue by Vinndimon** [zanna-37/hass-swipe-navigation#72]
The new panel UI called Grace was added in [HA 2024.3](https://www.home-assistant.io/blog/2024/03/06/release-20243/).

On mobile, if I try to edit the panel in Grace and start dragging an element horizontally, swipe navigation switches me to the next tab. It makes drag 'n' drop incompatible with the current iteration of swipe navigation.

**Comment by zanna-37** [comment]
You are very right, good catch.

**Comment by zanna-37** [comment]
Can you test the new Beta `v1.13.3`? Everything should be working.

**Comment by Vinndimon** [comment]
@zanna-37 the beta version fixes the issue for me. Thank you!
