### ISSUE TITLE
Swipe to open HA sidebar changes tabs

### ISSUE THREAD

**Issue by Stooovie** [zanna-37/hass-swipe-navigation#78]
In the ios HA app, swiping right over the left edge to reveal the HA app sidebar, Lovelace tabs change beneath it. I don't remember this being an issue before. 

HA 2024.7.2, Swipe Navigation 1.13.3, HA app 2024.6.

**Comment by Write** [comment]
Can confirm.

**Comment by zanna-37** [comment]
As stated in many places such as [Reddit](https://www.reddit.com/r/homeassistant/comments/12dznof/can_no_longer_swipe_to_side_bar/), [HA Forum](https://community.home-assistant.io/t/swipe-for-sidebar/556909/4), [GH issue](https://github.com/zanna-37/hass-swipe-navigation/issues/45#issuecomment-1498410713), I think Home Assistant stopped supporting the gesture long ago. Nothing I can do here unfortunately.
