### ISSUE TITLE
Swipe jumps 2 tabs

### ISSUE THREAD

**Issue by redwngsrul** [zanna-37/hass-swipe-navigation#88]
As the title describes it, when I swipe my finger left or right, my frontend jumps 2 tabs left or right. It has done this for quite awhile too across many versions of HA and the swipe nav app. Sorry, I just decided to raise the issue. Not sure when it started but here's my current specs.

Versions
Home Assistant - 2024.11.1
Supervisor - 2024.11.3
OS - 13.2
Frontend - 20241106.2
HACS - 2.0.1
Home Assistant Swipe Navigation - 1.15.0
Android - 14
HA Android App - 2024.10.3-full

Any ideas or suggestions would be greatly appreciated. Thanks.

**Comment by zanna-37** [comment]
Don't worry, saying things out loud helps thinking. =)
Glad you solved the problem.
Have a nice day.
